# Prework Assignment

### General Background Questions

1. Why is version control important in science?

In [1]:
# Version control better equips individual researchers and facilitates group collaboration. For the individual, version control, more specifically Git, offers a place for researchers to pick up where others have left off, check for errors and find innovative solutions. For the group project, Git makes the meshing of individual contributions more seamless. 


2. What kind of research artifacts can we track with Git?

In [1]:
# Git can track manuscripts, notes, datasets, and statistical code and figures. 

3. What are the three main things that can go wrong in a data science project?

In [1]:
# Either the data isn’t what you wanted, the model doesn’t work well, or you were solving the wrong problem. 


### Python Background Questions

These short exercises are a way to familiarize yourself with python. If you find these exercises too difficult, don’t worry! We will review the basics the first day to make sure we are all comfortable coding in Python.

Please save your work in this document and `git push` them to the `prework-assignment` repo.

----------------------------------------------------------------

### Problem 1: Basic Operations

You are at Vanessa's Vegan Cafe and you loved it so much you wanna leave a tip. Write a function that takes the amount owed and calculates how much money you pay with an 18% tip. If functions still scare you, just the solution code will do.

In [2]:
amountOwed=float(input('enter the cost of the food: '))
Total=amountOwed *1.18
print(str(round(Total,2)) + ' is the total of the meal')


enter the cost of the food: 2
2.36 is the total of the meal


----------------------------------------------------------------

### Problem 2: Lists

I have a fortune cookie that says my lucky numbers are:

       [23, 54, 6, 8, 10078, 3]

Write a function that returns 3 lists (if functions still scare you, just the solution code will do)
   - replace the number 6 with 1
   - the above list in decreasing order
   - all values greater than 15

In [4]:
luckyNumbers =[23,54,6,8,10078,3]    # this is the original set of luckyNumbers
luckyNumbers[2]=1
print(luckyNumbers)                  # this is the set of luckyNumbers with a '1' replacing the '6'
import copy
largeToSmall=copy.copy(luckyNumbers)
largeToSmall.sort(reverse=True)
print(largeToSmall)                 # this is the list, with the '1' still replacing the '6', in decreasing order
higherNumbers=copy.copy(largeToSmall)
for i in higherNumbers:
    if i<=15:
        higherNumbers.remove(i)
for i in higherNumbers:
    if i<=15:
        higherNumbers.remove(i)
print (higherNumbers)                # this is the list of numbers above 15


[23, 54, 1, 8, 10078, 3]
[10078, 54, 23, 8, 3, 1]
[10078, 54, 23]


----------------------------------------------------------------

### Problem 3: Basic Operations

Let's now take the first step in coding some real data science. Write a statement that loads the `numpy` library into the interpreter and gives it an alias of `np`.

In [5]:
import numpy as np

----------------------------------------------------------------

### Problem 4: Numpy

Generated a 10x10 `numpy` array with random numbers and slice the array to get the 2nd and 3rd column. Also calculate the average of 6th column using `numpy`.

In [7]:
import numpy as np
array1=np.random.randint(0,100, size=[10,10])
print(array1)
print(array1[:,1:3])
col6=array1[:,5:6]
np.average(col6)

[[18 85 97  0 95 95 60 85 47 91]
 [44 13 23 53 75 44 56 92 57  6]
 [16 11 72  1 76 39 49 69 67 56]
 [54 88  9 22 27 85  3 54 34 79]
 [84 68 79 92 43  2 64  8  6 25]
 [19 85 28 20 89 85 91 66 59 53]
 [57 15 17 52 35 69 85 37 97 15]
 [91 42 24 80 44 84 57 97 18 12]
 [90 31 15  1 33 69 46 23 62 25]
 [60 10 19 81 67 64  1 94 51 55]]


63.6

----------------------------------------------------------------

##### That's it! We look forward to seeing you in class!